<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="v0 → v18: every prompt change, its rationale, and measured accuracy on each dataset slice.">

<title>Prompt Version Changelog – RVL-CDIP Document Classifier</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-df5af9fadd5181f8cda5c5b9e347827e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">RVL-CDIP Document Classifier</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-methods--reference" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Methods &amp; Reference</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-methods--reference">    
        <li>
    <a class="dropdown-item" href="../methods/overview.html">
 <span class="dropdown-text">Pipeline &amp; Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methods/document-processor.html">
 <span class="dropdown-text">Document Processor Module</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methods/cli-commands.html">
 <span class="dropdown-text">CLI Commands Reference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methods/classes.html">
 <span class="dropdown-text">Document Classes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../methods/prompt-rules-provenance.html">
 <span class="dropdown-text">Prompt Rules Provenance</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-results" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Results</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-results">    
        <li>
    <a class="dropdown-item" href="../results/headline-results.html">
 <span class="dropdown-text">Headline Results</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../results/experiment-log.html">
 <span class="dropdown-text">Braintrust Experiment Log</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../results/experiment-reports.html">
 <span class="dropdown-text">Experiment Reports</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../results/confusion-matrices.html">
 <span class="dropdown-text">Confusion Matrices</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../results/gemini-800-notes.html">
 <span class="dropdown-text">Gemini 2.5 Flash — 800 Images</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../results/gemini-160-notes.html">
 <span class="dropdown-text">Gemini 2.5 Flash — 160 Images</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-prompt-evolution" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Prompt Evolution</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-prompt-evolution">    
        <li>
    <a class="dropdown-item" href="../prompts/prompt-changelog.html">
 <span class="dropdown-text">Prompt Version Changelog</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../prompts/enhancements.html">
 <span class="dropdown-text">Data-Backed Enhancement List</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cost-analysis" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cost Analysis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cost-analysis">    
        <li>
    <a class="dropdown-item" href="../cost/cost-estimation.html">
 <span class="dropdown-text">OpenRouter Cost Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cost/cost-projections.html">
 <span class="dropdown-text">Cost Projections</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-monte-carlo" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Monte Carlo</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-monte-carlo">    
        <li>
    <a class="dropdown-item" href="../montecarlo/overview.html">
 <span class="dropdown-text">Monte Carlo Simulation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/prompt-ablation.html">
 <span class="dropdown-text">Prompt Ablation — Paired Bootstrap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/ensemble-voting.html">
 <span class="dropdown-text">Ensemble Voting — Accuracy vs K</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/routing-abstention.html">
 <span class="dropdown-text">Confidence-Gated Escalation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/failure-pipeline.html">
 <span class="dropdown-text">Failure Pipeline Simulation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/exemplar-mining.html">
 <span class="dropdown-text">Few-Shot Exemplar Mining</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/ale-stopword.html">
 <span class="dropdown-text">ALE + Stop-Word Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/verification.html">
 <span class="dropdown-text">Verification Evals — Measured vs Simulated</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../montecarlo/corpus-summary.html">
 <span class="dropdown-text">Monte Carlo Corpus Summary</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-appendix" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Appendix</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-appendix">    
        <li>
    <a class="dropdown-item" href="../appendix/misclassifications.html">
 <span class="dropdown-text">Misclassification Reasoning — 1,120-Image v11.8 Run</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Exios66/AMFAM_capstone"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#v11-estimate-vs-bill-rule" id="toc-v11-estimate-vs-bill-rule" class="nav-link active" data-scroll-target="#v11-estimate-vs-bill-rule">v11 — Estimate vs Bill Rule</a></li>
  <li><a href="#v11.5-extended-money-only-records" id="toc-v11.5-extended-money-only-records" class="nav-link" data-scroll-target="#v11.5-extended-money-only-records">v11.5 — Extended Money-Only Records</a></li>
  <li><a href="#v11.6-intermediate" id="toc-v11.6-intermediate" class="nav-link" data-scroll-target="#v11.6-intermediate">v11.6 — (Intermediate)</a></li>
  <li><a href="#v11.7-minimal-edit-set-d-a-b" id="toc-v11.7-minimal-edit-set-d-a-b" class="nav-link" data-scroll-target="#v11.7-minimal-edit-set-d-a-b">v11.7 — Minimal Edit Set D + A + B</a></li>
  <li><a href="#v11.8-fix-1-form-vs-budget-authorization-fix-2-memo-vs-letter" id="toc-v11.8-fix-1-form-vs-budget-authorization-fix-2-memo-vs-letter" class="nav-link" data-scroll-target="#v11.8-fix-1-form-vs-budget-authorization-fix-2-memo-vs-letter">v11.8 — Fix 1 (Form-vs-Budget Authorization) + Fix 2 (Memo-vs-Letter)</a></li>
  <li><a href="#v11.9-narrow-edit-bs-financial-chartbudget-carve-out" id="toc-v11.9-narrow-edit-bs-financial-chartbudget-carve-out" class="nav-link" data-scroll-target="#v11.9-narrow-edit-bs-financial-chartbudget-carve-out">v11.9 — Narrow Edit B’s Financial-Chart→Budget Carve-Out</a></li>
  <li><a href="#v12-major-rewrite-function-based-invoice-vs-budget" id="toc-v12-major-rewrite-function-based-invoice-vs-budget" class="nav-link" data-scroll-target="#v12-major-rewrite-function-based-invoice-vs-budget">v12 — Major Rewrite (Function-Based Invoice vs Budget)</a></li>
  <li><a href="#v13-specialist-periodicals-scientific-research-records" id="toc-v13-specialist-periodicals-scientific-research-records" class="nav-link" data-scroll-target="#v13-specialist-periodicals-scientific-research-records">v13 — Specialist Periodicals + Scientific Research Records</a></li>
  <li><a href="#v14-production-precedence-rules" id="toc-v14-production-precedence-rules" class="nav-link" data-scroll-target="#v14-production-precedence-rules">v14 — Production Precedence Rules</a></li>
  <li><a href="#v15-function-first-regression-repair" id="toc-v15-function-first-regression-repair" class="nav-link" data-scroll-target="#v15-function-first-regression-repair">v15 — Function-First Regression Repair</a></li>
  <li><a href="#summary-table" id="toc-summary-table" class="nav-link" data-scroll-target="#summary-table">Summary Table</a></li>
  <li><a href="#best-results-by-dataset" id="toc-best-results-by-dataset" class="nav-link" data-scroll-target="#best-results-by-dataset">Best Results by Dataset</a></li>
  <li><a href="#v16-v11.9-two-worked-examples-estimateinvoice-handwrittenletter" id="toc-v16-v11.9-two-worked-examples-estimateinvoice-handwrittenletter" class="nav-link" data-scroll-target="#v16-v11.9-two-worked-examples-estimateinvoice-handwrittenletter">v16 — v11.9 + Two Worked Examples (Estimate→Invoice, Handwritten→Letter)</a></li>
  <li><a href="#v17-simplified-financial-rules-handwritten-letter-override" id="toc-v17-simplified-financial-rules-handwritten-letter-override" class="nav-link" data-scroll-target="#v17-simplified-financial-rules-handwritten-letter-override">v17 — Simplified Financial Rules + Handwritten → Letter Override</a></li>
  <li><a href="#cross-model-v11.8-validation-runs-aug-2026" id="toc-cross-model-v11.8-validation-runs-aug-2026" class="nav-link" data-scroll-target="#cross-model-v11.8-validation-runs-aug-2026">Cross-model v11.8 Validation Runs (Aug 2026)</a></li>
  <li><a href="#v17.1-surgical-calibration-counter-examples-aug-2026" id="toc-v17.1-surgical-calibration-counter-examples-aug-2026" class="nav-link" data-scroll-target="#v17.1-surgical-calibration-counter-examples-aug-2026">v17.1 — Surgical Calibration + Counter-Examples (Aug 2026)</a></li>
  <li><a href="#v18-monte-carlo-exemplar-appendix-aug-2026-experimental" id="toc-v18-monte-carlo-exemplar-appendix-aug-2026-experimental" class="nav-link" data-scroll-target="#v18-monte-carlo-exemplar-appendix-aug-2026-experimental">v18 — Monte Carlo Exemplar Appendix (Aug 2026, EXPERIMENTAL)</a></li>
  <li><a href="#v17.2-three-slice-generalization-aug-2026" id="toc-v17.2-three-slice-generalization-aug-2026" class="nav-link" data-scroll-target="#v17.2-three-slice-generalization-aug-2026">v17.2 — Three-Slice Generalization (Aug 2026)</a></li>
  <li><a href="#v0-function-not-subject-baseline-aug-2026" id="toc-v0-function-not-subject-baseline-aug-2026" class="nav-link" data-scroll-target="#v0-function-not-subject-baseline-aug-2026">v0 — Function-Not-Subject Baseline (Aug 2026)</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Prompt Version Changelog</h1>
</div>

<div>
  <div class="description">
    v0 → v18: every prompt change, its rationale, and measured accuracy on each dataset slice.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This document tracks the changes between prompt iterations (v11 through v15) for the qwen3.7-flash document classifier.</p>
<hr>
<section id="v11-estimate-vs-bill-rule" class="level2">
<h2 class="anchored" data-anchor-id="v11-estimate-vs-bill-rule">v11 — Estimate vs Bill Rule</h2>
<p><strong>Baseline prompt for the estimate-vs-bill disambiguation work.</strong></p>
<ul>
<li><strong>Check 7 (Financial Document):</strong> Restored v9 wording for agency/vendor ESTIMATE documents with unit prices/amounts/totals (invoice), and added concrete bill signals (“EST NO”, “REVISES EST”, “PRIOR ADJUSTMENTS”, “EST AMT LESS C/D”, original-vs-present estimate columns, “BILLING TYPE PROGRESSIVE”).</li>
<li><strong>Budget carve-out narrowed:</strong> A pure planning recap with no billing apparatus (e.g., “OUTDOOR ESTIMATE RECAP” bus-shelter planning) stays budget. Check stubs remain budget even when columns are headed “INVOICE DATE/NO/AMOUNT”.</li>
<li><strong>Worked examples:</strong> 4th example teaches estimate-change-order → invoice case.</li>
</ul>
<p><strong>Rationale:</strong> v10 had routed three agency estimate documents to budget because the invoice bullet was too narrow (“billing document for COMPLETED work…listing ACTUAL billable charges”). v11 restored the broader v9 wording to recover invoice coverage.</p>
<hr>
</section>
<section id="v11.5-extended-money-only-records" class="level2">
<h2 class="anchored" data-anchor-id="v11.5-extended-money-only-records">v11.5 — Extended Money-Only Records</h2>
<p><strong>Extended clarification for money-only records and periodic customer statements.</strong></p>
<ul>
<li><strong>Check 7 (invoice):</strong> Added landlord’s rent/lease statement for a specific period as invoice (bills one-off service period, not ongoing account).</li>
<li><strong>Check 7 (budget):</strong> Clarified campaign-contribution/expenditure requests, contribution-request checklists, grant/contribution requests with recipient and amount as budget (internal money requests). Added campaign-contribution/expenditure statements/disclosures and financial/money-data tables (price/value estimates, price-to-earnings, budget-vs-actual, stock/investment figures) as budget.</li>
<li><strong>Check 10 (form):</strong> Explicitly excluded campaign-contribution requests/checklists/statements and financial or money-data tables from form.</li>
</ul>
<p><strong>Rationale:</strong> The model was routing money-only records to form because they had approval blocks or field layouts. v11.5 made explicit that bare money requests (amount + recipient, or financial data tables) are budget, not form.</p>
<hr>
</section>
<section id="v11.6-intermediate" class="level2">
<h2 class="anchored" data-anchor-id="v11.6-intermediate">v11.6 — (Intermediate)</h2>
<p>No build script preserved. Likely minor tweaks between v11.5 and v11.7.</p>
<hr>
</section>
<section id="v11.7-minimal-edit-set-d-a-b" class="level2">
<h2 class="anchored" data-anchor-id="v11.7-minimal-edit-set-d-a-b">v11.7 — Minimal Edit Set D + A + B</h2>
<p><strong>Deliberately minimal 3-edit set (C and E skipped to reduce regression risk).</strong></p>
<ul>
<li><strong>Edit D (Check 7 voucher vs check-stub):</strong> Voucher is a payment instrument that BILLS a named payee for named goods/services/charges (invoice). Check face/check stub is the DISBURSEMENT instrument (budget), even when stub columns are headed “INVOICE DATE/NO/AMOUNT”.</li>
<li><strong>Edit A (Check 8 rate-data chart):</strong> A labeled product/parameter rate-data chart (e.g., statistical process-control chart titled with product name plotting measured property against spec limits) is specification even without “shall/must” text.</li>
<li><strong>Edit B (Check 10 standalone-chart carve-out):</strong> A standalone labeled chart is form only when it holds generic administrative/log data. A chart of a product’s measured parameters against spec limits → specification (check 8). A financial/money chart → budget (check 7). A research-measurement chart → scientific_report (check 13).</li>
</ul>
<p><strong>Rationale:</strong> v11 had two 160-set misses: <code>jow70f00</code> (form → budget, ambiguous grant payment) and <code>tqi16e00</code> (budget → invoice, planning recap with estimate numbers). v11.7 targeted structural disambiguation (voucher vs check-stub) and chart-type routing (product/parameter charts, financial charts) with minimal changes to avoid regressions.</p>
<p><strong>Result:</strong> 160-set: 156/159 (98.1%). Eval 56-set: 20/56 (35.7%) — best eval yet (v11.5 = 16/56, v11.6 = 17/56).</p>
<hr>
</section>
<section id="v11.8-fix-1-form-vs-budget-authorization-fix-2-memo-vs-letter" class="level2">
<h2 class="anchored" data-anchor-id="v11.8-fix-1-form-vs-budget-authorization-fix-2-memo-vs-letter">v11.8 — Fix 1 (Form-vs-Budget Authorization) + Fix 2 (Memo-vs-Letter)</h2>
<p><strong>Two targeted fixes for v11.7’s remaining 160-set misses.</strong></p>
<ul>
<li><strong>Fix 1 (Form-vs-budget authorization):</strong> Budget money-only clause narrowed to bare amount-only requests ONLY. A project-funding authorization/approval form that names the work to be funded, carries finance-data/expense-code fields (e.g., budgeted department/expense code), and has an approval block is form (check 10), not budget — even when it states an amount (e.g., “AUTHORIZATION REQUEST” for $690,000 to perform a named study). Caveat explicitly includes AUTHORIZATION REQUEST / project-funding forms.</li>
<li><strong>Fix 2 (Memo-vs-letter):</strong> By-name memo rule requires an explicit INTERNAL TITLE/DIVISION in the address line; do not infer internal vs.&nbsp;external from pronoun usage in the prose. A dated note addressed to a bare name with an honorific (e.g., “Mr.&nbsp;T. E. Sandefur:”) — no internal title/division, no TO:/FROM:/RE:/SUBJECT: block, no “Dear …” salutation, and no closing signature — is a letter (external addressee), not a memo.</li>
</ul>
<p><strong>Rationale:</strong> v11.7 had three 160-set misses: <code>yvp54d00</code> (form → budget, AUTHORIZATION REQUEST $690,000), <code>cpt85d00</code> (letter → memo, “Mr.&nbsp;T. E. Sandefur”), <code>tqi16e00</code> (budget → invoice). Fix 1 targets the authorization-request form; Fix 2 targets the bare-name external addressee case.</p>
<p><strong>Result:</strong> 160-set: 157/158 (99.4%) — best ever. All three v11.7 misses fixed. Eval 56-set: 18/56 (32.1%) — regression vs v11.7’s 20/56. Two eval rows recovered (<code>form__0005</code>, <code>spec__0019</code>), but four regressed (<code>presentation__0001</code>, <code>presentation__0011</code> → budget; <code>spec__0017</code> → form; <code>jed71e00</code> → presentation).</p>
<hr>
</section>
<section id="v11.9-narrow-edit-bs-financial-chartbudget-carve-out" class="level2">
<h2 class="anchored" data-anchor-id="v11.9-narrow-edit-bs-financial-chartbudget-carve-out">v11.9 — Narrow Edit B’s Financial-Chart→Budget Carve-Out</h2>
<p><strong>Three edits that narrow Edit B so titled/designed deck charts no longer fall into budget.</strong></p>
<ul>
<li><strong>Edit 1 (Check 10 carve-out narrowed):</strong> A product/parameter rate-data chart → specification. A research/measurement chart → scientific_report. A financial/money chart → budget ONLY when it is a standalone data table used for money planning or tracking (a ledger, budget-vs-actual, price/value table). A financial chart presented as a TITLED, DESIGNED DECK CHART (a chart page styled as a slide with its own title/caption, company logo/date, or chart-per-page deck look, e.g., a “brand shares” pie chart or “performance triggers” table page) → presentation (check 9), not budget.</li>
<li><strong>Edit 2 (Check 9 hardened):</strong> A titled/designed deck chart IS a presentation slide; don’t route it to budget. The check-10 carve-out routes money charts to budget only when they are standalone planning/tracking data tables, not when they are titled deck charts.</li>
<li><strong>Edit 3 (Calibration):</strong> Keep the deck-chart exception visible next to the general chart rule.</li>
</ul>
<p><strong>Rationale:</strong> v11.8’s Edit B carve-out (“a financial/money chart is budget”) was too broad — it routed titled designed deck charts to budget ahead of check 9. The eval set had two presentation→budget regressions (<code>presentation__0001</code>, <code>presentation__0011</code>) from v11.7 to v11.8. v11.9 narrows the carve-out to standalone planning/tracking tables only.</p>
<p><strong>Result:</strong> Eval 56-set: 20/56 (35.7%) — ties v11.7’s best, +2 over v11.8’s 18/56. Both presentation→budget regressions recovered, plus bonus fix of <code>jed71e00</code> (form → presentation, also v11.8’s 160-set miss). Cost: <code>form__0005</code> (a v11.8 Fix-1 success) regressed to invoice; new <code>news_article__0008</code> → memo miss.</p>
<hr>
</section>
<section id="v12-major-rewrite-function-based-invoice-vs-budget" class="level2">
<h2 class="anchored" data-anchor-id="v12-major-rewrite-function-based-invoice-vs-budget">v12 — Major Rewrite (Function-Based Invoice vs Budget)</h2>
<p><strong>Complete rewrite of checks 7, 9, 10 with new calibration and worked examples.</strong></p>
<ul>
<li><strong>Edit A (Check 7 complete rewrite):</strong> DECIDE BY FUNCTION, NOT BY HEADINGS. Invoice: page charges or requests payment for goods SOLD or services PERFORMED. Budget: internal money planning, tracking, or disbursement. Added explicit guidance on purchase orders (invoice when listing line items/quantities/prices/total), vouchers (payment instrument, invoice), hotel/motel bills (invoice), landlord’s rent/lease statements (invoice), agency estimates/change orders (invoice when listing actual charges/totals, budget when only projecting future spend), checks/check stubs (budget).</li>
<li><strong>Edit B (Check 9 last-sentence rewrite):</strong> A chart-per-page deck exhibit (titled chart, pie chart, flowchart, or data table that is a SINGLE visual on a slide-styled page with descriptive title, corporate branding, footer date/code) IS a slide (presentation), not a form. A dense data-RECORD table (multi-row/multi-column records log, data-capture sheet, chart data table with generic row labels) is form (check 10).</li>
<li><strong>Edit C (Check 10 data-table clause):</strong> Covers dense multi-row data-RECORD tables (records logs, data-capture sheets, chart data tables with generic row labels). NOT covered: single-exhibit chart/table on slide-styled page (presentation); titled product-analysis table keyed to product/material (specification).</li>
<li><strong>Edit D (Calibration trim):</strong> Updated calibration section with refined rules for form/scientific_report/handwritten/news_article/presentation over/under-prediction.</li>
<li><strong>Edit E (Worked examples):</strong> Updated worked examples for agency estimate change order (invoice) vs planning recap (budget).</li>
</ul>
<p><strong>Rationale:</strong> v11.5-v11.9 incremental edits had accumulated complexity. v12 rewrites check 7 from scratch with a function-based decision framework (bill vs plan/track/statement), clarifies check 9 for chart-per-page deck exhibits vs dense data-record tables, and streamlines calibration.</p>
<hr>
</section>
<section id="v13-specialist-periodicals-scientific-research-records" class="level2">
<h2 class="anchored" data-anchor-id="v13-specialist-periodicals-scientific-research-records">v13 — Specialist Periodicals + Scientific Research Records</h2>
<p><strong>Built from v11.9. Extends scientific_publication to specialist periodicals and scientific_report to research records.</strong></p>
<ul>
<li><strong>Check 6 (Published evidence):</strong> Include a dated, titled science, medical, engineering, or technical periodical page whose own masthead identifies that specialist publication (e.g., a science magazine or medical trade paper), even when it lacks volume/issue/DOI.</li>
<li><strong>Check 12 (News article caveat):</strong> Don’t use general-news caveat for specialist science, medical, engineering, or technical periodicals. A specialist periodical with its own dated masthead is scientific_publication, not news_article, even if its page uses magazine/news typography or a section title such as “Monitor” or “World Wide Report”.</li>
<li><strong>Check 10 (Form carve-out):</strong> Generic administrative forms remain form, but a page whose fields, tables, signatures, or handwritten entries document a scientific experiment, laboratory result, compound test, analytical measurement, protocol review, or technical research report → scientific_report (check 13), not form.</li>
<li><strong>Check 10 (additional):</strong> It does NOT cover scientific/laboratory research records merely because they use fields, tables, QA sign-offs, or a report cover.</li>
</ul>
<p><strong>Rationale:</strong> The model was routing specialist science/medical/technical periodicals (with their own mastheads) to news_article because they used magazine/news typography. It was also routing scientific research records (experiments, lab results, compound tests) to form because they used structured fields/tables. v13 extends scientific_publication to specialist periodicals and scientific_report to research records.</p>
<p><strong>Result:</strong> v2 160-set: 137/159 (86.2%).</p>
<hr>
</section>
<section id="v14-production-precedence-rules" class="level2">
<h2 class="anchored" data-anchor-id="v14-production-precedence-rules">v14 — Production Precedence Rules</h2>
<p><strong>Built from v13. Adds final authority rules for conflicting cues.</strong></p>
<ul>
<li><strong>Added section:</strong> “v14 production precedence (final authority)” with explicit rules:
<ol type="1">
<li><strong>Financial function beats layout:</strong> Invoice for vendor/agency billing specific good/service/job. Budget for internal planning/tracking/recurring statements/checks. Form for single authorization/request with approval fields (even with large dollar amount).</li>
<li><strong>Generic form is not a technical catch-all:</strong> Form only when primary purpose is administrative data capture/approval and no stronger document function. Page documenting experiment/sample/compound/protocol/measurement/lab result/research study → scientific_report unless clearly product/material documentation.</li>
<li><strong>Additional precedence rules</strong> (from truncated output): Likely covers other recurring boundary decisions.</li>
</ol></li>
</ul>
<p><strong>Rationale:</strong> v13 extended scientific_publication and scientific_report, but the model still had edge cases where layout cues (structured fields, approval blocks, dollar amounts) overrode document function. v14 makes the recurring boundary decisions explicit as final authority rules.</p>
<p><strong>Result:</strong> v2 160-set retry: 136/160 (85.0%).</p>
<hr>
</section>
<section id="v15-function-first-regression-repair" class="level2">
<h2 class="anchored" data-anchor-id="v15-function-first-regression-repair">v15 — Function-First Regression Repair</h2>
<p><strong>Built from the validated v13 base after analyzing the v14 reasoning traces.</strong></p>
<ul>
<li><strong>Financial boundary:</strong> Requires positive billing evidence for <code>invoice</code>; estimate numbers, revisions, agency letterhead, projected periods, and quoted totals alone remain <code>budget</code> when the page plans future spend. Purchase orders and authorization requests remain <code>form</code> when their function is approval.</li>
<li><strong>Letter boundary:</strong> Recognizes recipient-directed prose with a salutation or closing as <code>letter</code> without requiring letterhead or a complete street address. Complete handwritten letters remain <code>letter</code>; freeform notes and cards remain <code>handwritten</code>.</li>
<li><strong>Email boundary:</strong> Preserves genuine mail-client evidence requirements so phone-message logs, voicemail records, fax metadata, and generic From/To forms do not become email.</li>
<li><strong>Form/questionnaire boundary:</strong> Requires a respondent-facing survey instrument for <code>questionnaire</code>; retains <code>form</code> for administrative capture and QC sheets.</li>
<li><strong>Technical boundary:</strong> Separates normative product requirements (<code>specification</code>), filled QC/data-capture sheets (<code>form</code>), and study findings/results (<code>scientific_report</code>).</li>
<li><strong>Presentation/news boundary:</strong> Requires explicit deck or promotional function instead of relying on rotation, scan borders, sparse tables, or isolated mastheads.</li>
<li><strong>Output contract:</strong> Requires exactly one parser-safe <code>&lt;label&gt;...&lt;/label&gt;</code> result.</li>
</ul>
<p><strong>Rationale:</strong> v14 fell to 85.0% on <code>fixed_size_sampled_v2</code>, with repeated budget/invoice and form-boundary errors. Its final precedence rules over-weighted weak visual or lexical cues and contradicted function-based evidence in the traces.</p>
<p><strong>Validation assets:</strong> Adds two disjoint 160-image Braintrust slices, <code>fixed_size_sampled_v3</code> and <code>fixed_size_sampled_v4</code>, sampled primarily from the full Hugging Face <code>chainyo/rvl-cdip</code> test split and using the Kaggle test checkout only as a fallback when the Hugging Face source cannot satisfy disjoint quotas.</p>
<hr>
</section>
<section id="summary-table" class="level2">
<h2 class="anchored" data-anchor-id="summary-table">Summary Table</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Version</th>
<th>Based On</th>
<th>Key Changes</th>
<th>160-set</th>
<th>320-set</th>
<th>480-set</th>
<th>Eval 56</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>v11</td>
<td>v10</td>
<td>Estimate vs bill rule</td>
<td>156/158 (98.7%)</td>
<td>266/317 (83.9%)</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>v11.5</td>
<td>v11</td>
<td>Extended money-only records</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td>v11.6</td>
<td>v11.5</td>
<td>(Intermediate)</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>v11.7</td>
<td>v11.6</td>
<td>Edit D+A/B (voucher/check-stub, rate-data chart, standalone-chart)</td>
<td>156/159 (98.1%)</td>
<td>—</td>
<td>—</td>
<td>20/56 (35.7%)</td>
</tr>
<tr class="odd">
<td>v11.8</td>
<td>v11.7</td>
<td>Fix 1 (authorization form) + Fix 2 (memo vs letter)</td>
<td>157/158 (99.4%)</td>
<td>279/320 (87.2%)</td>
<td>424/476 (89.1%)</td>
<td>18/56 (32.1%)</td>
</tr>
<tr class="even">
<td>v11.9</td>
<td>v11.8</td>
<td>Narrow Edit B (titled deck charts → presentation)</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>20/56 (35.7%)</td>
</tr>
<tr class="odd">
<td>v12</td>
<td>v11.6</td>
<td>Major rewrite (function-based invoice/budget, chart-per-page deck)</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>v13</td>
<td>v11.9</td>
<td>Specialist periodicals + scientific research records</td>
<td>137/159 (86.2%) [v2]</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="odd">
<td>v14</td>
<td>v13</td>
<td>Production precedence rules</td>
<td>136/160 (85.0%) [v2 retry]</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="best-results-by-dataset" class="level2">
<h2 class="anchored" data-anchor-id="best-results-by-dataset">Best Results by Dataset</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dataset</th>
<th>Best Version</th>
<th>Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>160-image (original)</td>
<td>v11.8</td>
<td>157/158 (99.4%)</td>
</tr>
<tr class="even">
<td>320-image</td>
<td>v11.8</td>
<td>279/320 (87.2%)</td>
</tr>
<tr class="odd">
<td>480-image</td>
<td>v11.8</td>
<td>424/476 (89.1%)</td>
</tr>
<tr class="even">
<td>Eval 56</td>
<td>v11.7 / v11.9</td>
<td>20/56 (35.7%)</td>
</tr>
<tr class="odd">
<td>160-image v2</td>
<td>v11.9</td>
<td>137/159 (86.2%)</td>
</tr>
</tbody>
</table>
<p><strong>Note:</strong> v11.8 generalizes best to larger, noisier datasets (320, 480). v11.7 and v11.9 tie on the eval 56-set. v13 and v14 target specialist periodicals and scientific research records but show lower accuracy on the v2 dataset.</p>
<hr>
</section>
<section id="v16-v11.9-two-worked-examples-estimateinvoice-handwrittenletter" class="level2">
<h2 class="anchored" data-anchor-id="v16-v11.9-two-worked-examples-estimateinvoice-handwrittenletter">v16 — v11.9 + Two Worked Examples (Estimate→Invoice, Handwritten→Letter)</h2>
<p><strong>Appended two worked examples to the v11.9 prompt to target the top confusion pairs from prior evaluations.</strong></p>
<ul>
<li><strong>Worked example 1:</strong> Estimate vs Invoice — a “DATABASE MARKETING ESTIMATE” with PREVIOUS/CURRENT ESTIMATE columns showing planned agency spending is budget, not invoice (no payment demand).</li>
<li><strong>Worked example 2:</strong> Handwritten letter vs handwritten note — a complete handwritten letter with salutation, prose body, and closing remains letter, not handwritten.</li>
<li><strong>Prompt length:</strong> 51,753 chars (v11.9 = 50,254).</li>
</ul>
<p><strong>Result (multispect on 3 slices):</strong> | Slice | Accuracy | Failure rate | |——-|———-|————-| | v1 (test_images) | 154/160 (96.2%) | 1 failed row | | v2 (HF mirror) | 134/160 (83.8%) | 6 failed rows | | v3 (HF mirror) | 127/160 (79.4%) | 9 failed rows |</p>
<p><strong>Findings:</strong> Worked examples did not prevent the top confusions (handwritten→letter = 10, budget→invoice = 7 across slices). 16 total failed rows (13 finish_reason=length, 3 provider errors). v2/v3 HF-mirror source is ~15pp harder than v1 test_images source, independent of prompt version.</p>
<hr>
</section>
<section id="v17-simplified-financial-rules-handwritten-letter-override" class="level2">
<h2 class="anchored" data-anchor-id="v17-simplified-financial-rules-handwritten-letter-override">v17 — Simplified Financial Rules + Handwritten → Letter Override</h2>
<p><strong>Data-driven rebuild of the v11.9 check-7 (financial) rules, eliminating the agency-estimate sub-protocol that caused v11.9–v16’s budget→invoice errors. Adds explicit LETTER/MEMO OVERRIDE in check-2 (handwritten) to enforce ordered-checklist precedence.</strong></p>
<p>Driven by three root causes identified in the v16 multispect evaluation (<code>reports/v16_multislice_evaluation_report.md</code>):</p>
<ol type="1">
<li><p><strong>Provider failures (16 rows / 3.3%)</strong> — 13 finish_reason=length (qwen3.7-flash exhausts reasoning tokens on the bloated check-7 section) → <strong>Fix:</strong> Trim check-7 from 6,284 chars to ~1,100 chars (simplified invoice=payment-demand, budget=planning, estimate=budget). Reduced reasoning effort to <code>medium</code>. Raised MAX_TOKENS_CAP to 32,768. Added 300s HTTP timeout.</p></li>
<li><p><strong>Slice source quality gap (~15pp)</strong> — v2/v3 (HF mirror) images are inherently harder than v1 (test_images) → <strong>Mitigation:</strong> Stronger rules should be more robust across sources.</p></li>
<li><p><strong>Prompt regression from v11.8’s 99.4%</strong> — the agency-estimate sub-protocol caused the model to misclassify budgets (planning estimates) as invoices when “PREVIOUS/CURRENT ESTIMATE” revision columns were present. → <strong>Fix:</strong> Removed the entire agency-estimate sub-protocol. The rule is now simple: “A document titled ESTIMATE is budget — it PLANS spending. Only an explicit payment demand (Amount Due, Pay, Invoice header) makes it invoice.”</p></li>
</ol>
<p><strong>Key changes from v11.9/v16:</strong> - <strong>Check-7 (invoice):</strong> Replaced 2,450-char agency-estimate maze with a 250-char clean rule: payment demand = invoice. - <strong>Check-7 (budget):</strong> Replaced 3,030-char budget section (including the planning-recap vs agency-bill sub-protocol) with a 700-char clean rule: estimate = budget. - <strong>Check-2 (handwritten):</strong> Added “LETTER/MEMO OVERRIDE” bullet: if most of the page is handwritten, it IS handwritten — even with complete letter structure (salutation, body, closing) or memo layout (To/From/Re/Date headers). Check 2 fires before check 11; do not evaluate letter/memo for handwritten pages. - <strong>Prompt length:</strong> 46,277 chars — 3,977 shorter than v11.9, 5,476 shorter than v16.</p>
<p><strong>Infrastructure:</strong> - Reasoning effort reduced to <code>medium</code> for qwen models (was <code>high</code>). - MAX_TOKENS_CAP raised to 32,768 (was 16,384). - Failed rows now return ERROR: sentinel output and are scored as a tracked <code>failed</code> metric in Braintrust. - HTTP timeout (300s) on OpenAI client. - All eval runs now use <code>--manifest</code> for resumability.</p>
<hr>
</section>
<section id="cross-model-v11.8-validation-runs-aug-2026" class="level2">
<h2 class="anchored" data-anchor-id="cross-model-v11.8-validation-runs-aug-2026">Cross-model v11.8 Validation Runs (Aug 2026)</h2>
<p>The v11.8 prompt was evaluated across additional OpenRouter models on the original 160-image <code>fixed_size_sampled</code> slice, with each model running at its maximum reasoning effort. Temperature was varied per run (0.1 default, 0.3 for the qwen3.7-flash re-run, 0.2 for gemini-2.5-flash-lite).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Reasoning effort</th>
<th style="text-align: right;">Temp</th>
<th>160-set Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>qwen3.7-flash (temp 0.1 baseline)</td>
<td>high</td>
<td style="text-align: right;">0.1</td>
<td>157/158 (99.4%)</td>
</tr>
<tr class="even">
<td>qwen3.7-flash (temp 0.3)</td>
<td>high</td>
<td style="text-align: right;">0.3</td>
<td>157/159 (98.7%)</td>
</tr>
<tr class="odd">
<td>qwen3.5-35b-a3b</td>
<td>high</td>
<td style="text-align: right;">0.1</td>
<td>155/157 (98.7%)</td>
</tr>
<tr class="even">
<td>kimi-k2.6</td>
<td>xhigh</td>
<td style="text-align: right;">0.1</td>
<td>aborted mid-run (network outage)</td>
</tr>
<tr class="odd">
<td>gemini-2.5-flash-lite</td>
<td>max</td>
<td style="text-align: right;">0.2</td>
<td>139/160 (86.9%)</td>
</tr>
</tbody>
</table>
<p><strong>Findings so far:</strong></p>
<ul>
<li>qwen3.7-flash at temp 0.3 holds 98.7% but regresses <code>tqi16e00</code> (budget → invoice) that was fixed at temp 0.1; <code>jed71e00</code> (form → presentation) remains the recurring miss across models.</li>
<li>qwen3.5-35b-a3b matches the qwen3.7-flash accuracy (98.7%) on the 160-set but needs a larger max_tokens budget — long reasoning traces capped several rows even after doubling to 16k.</li>
<li>gemini-2.5-flash-lite at max reasoning scores 86.9% with zero failed rows; it uniquely resolves <code>jed71e00</code> but over-uses <code>specification</code> (memo/form/handwritten/letter pull) and still confuses <code>scientific_publication → scientific_report</code> and <code>budget → invoice</code>.</li>
<li>On the deliberately hard <code>qwen_v12_retroactive_eval</code> slice (52 rows, all v12 misses), qwen3.5-35b-a3b scores 30.8% (16/52); expected given the slice only contains known hard cases.</li>
<li>kimi-k2.6 run aborted ~109/160 due to a transient DNS outage against <code>api.braintrust.dev</code> that crashed the Braintrust logging thread; the partial experiment is not comparable.</li>
</ul>
<p>The temperature and reasoning-effort flags added to <code>braintrust_openrouter_input.py</code> record both settings in Braintrust experiment metadata for reproducibility.</p>
<hr>
</section>
<section id="v17.1-surgical-calibration-counter-examples-aug-2026" class="level2">
<h2 class="anchored" data-anchor-id="v17.1-surgical-calibration-counter-examples-aug-2026">v17.1 — Surgical Calibration + Counter-Examples (Aug 2026)</h2>
<p><strong>Data-driven corrections from v16 v2+v3 multi-slice failure analysis (320 images, 81.6% accuracy).</strong></p>
<ul>
<li><strong>Worked example — handwritten letter → handwritten.</strong> v16’s worked example #2 taught the model that “a complete handwritten letter remains letter.” This caused 7/44 misclassifications across both slices (35% of the handwritten class). The new worked example applies the LETTER/MEMO OVERRIDE: handwriting wins regardless of letter formatting.</li>
<li><strong>Worked example — agency estimate → budget.</strong> v16’s worked example #1 failed to prevent budget→invoice confusion (6/44 misclassifications). The new worked example reinforces the simplified check-7 rule: no payment demand = budget.</li>
<li><strong>Calibration — scientific_report vs specification.</strong> 2 scientific_report→specification errors and a budget→scientific_report outlier traced to the model misreading technical data tables as product specs. New sentence: “A research study’s own experimental data tables belong to scientific_report, not specification — specification requires the page’s PRIMARY function to be defining a product’s composition.”</li>
<li><strong>Calibration — news_article vs advertisement.</strong> 3 news_article→advertisement errors where the model fixated on embedded ad imagery. New sentence: “Judge newspaper/magazine pages by editorial intent, not embedded ads — a page with masthead, columns, and bylines is news_article even when it CONTAINS a branded advertisement.”</li>
</ul>
<p><strong>Token profile:</strong> +2,177 chars (+4.7%). v17.1 total: 48,462 chars vs v16: 51,753 chars. Still significantly lighter than v16 while carrying 2 more worked examples (6 total vs v16’s 6, but v16’s were actively harmful).</p>
<hr>
</section>
<section id="v18-monte-carlo-exemplar-appendix-aug-2026-experimental" class="level2">
<h2 class="anchored" data-anchor-id="v18-monte-carlo-exemplar-appendix-aug-2026-experimental">v18 — Monte Carlo Exemplar Appendix (Aug 2026, EXPERIMENTAL)</h2>
<p><strong>Data-driven worked examples mined by <code>monte_carlo_exemplars.py</code> from the joint corpus (4,641 rows / 1,512 images). Four correct traces whose runner-up named the decoy label for four of the top confusion pairs.</strong></p>
<ul>
<li><strong>letter vs memo (letter):</strong> OGILVY &amp; MATHER letterhead, external address, “Dear John:” salutation, “Yours truly,” closing → letter, not memo. Targets the #1 confusion pair (letter→memo: 53 corpus errors).</li>
<li><strong>MSDS (specification, not form):</strong> “MATERIAL SAFETY DATA SHEET” with INGREDIENTS / PHYSICAL DATA / FIRE AND EXPLOSION HAZARD DATA sections → check 8 precedes check 10. Targets specification→form (41 errors).</li>
<li><strong>PHS 398 biographical sketch (resume, not form):</strong> check 5 explicitly covers PHS 398 templates — biographical content decides, not the form-page label. Targets resume→form (21 errors).</li>
<li><strong>Survey instrument (questionnaire, not form):</strong> YES/NO + open-response questions → check 4 precedes check 10. Targets questionnaire→form (16 errors).</li>
</ul>
<p><strong>Rationale:</strong> The Monte Carlo near-miss analysis found 27.7% of current-line misses have the correct label as the stated runner-up — the model overrides its own best evidence. These four exemplars teach the runner-up-vs-final decision on the highest-frequency pairs. Selected pairs cover 131 of 767 corpus errors (17%).</p>
<p><strong>Status:</strong> EXPERIMENTAL — NOT the default (default remains v17.2). <strong>Verified on the exemplar slice (48 images): v18 scored 64.6% vs v17.2’s 68.8% (−4.2pp) — the exemplar appendix did NOT improve accuracy and slightly hurt.</strong> The measurement shows that adding more worked-example text does not fix the runner-up-vs-final decision; the follow-up should be a decision-rule change (e.g.&nbsp;“never override your own stated runner-up without new evidence”), not more exemplar verbosity. v18 is retained for reference but should not be promoted.</p>
<p><strong>Token profile:</strong> +1,714 chars vs v17.2 (50,678 → 52,392 chars; +3.4%).</p>
<hr>
</section>
<section id="v17.2-three-slice-generalization-aug-2026" class="level2">
<h2 class="anchored" data-anchor-id="v17.2-three-slice-generalization-aug-2026">v17.2 — Three-Slice Generalization (Aug 2026)</h2>
<p><strong>Data-driven corrections from v17.1 v1+v2+v3 combined analysis (480 images, 53 failures, ~89% accuracy).</strong></p>
<p>v17.1 successfully eliminated handwritten→letter (0 misses across all 3 slices) and length errors (4 vs v16’s 15). Five clusters survived the v17.1 fix:</p>
<ul>
<li><strong>invoice→budget (6) + budget→invoice (3) + invoice→form (4):</strong> 13 financial document failures in 480 images. The simplified check-7 reduced v16’s 20 financial failures but the form-override rule (“money function overrides form layout”) wasn’t consistently applied when invoices had form-like layouts.</li>
<li><strong>news_article→advertisement (3):</strong> The v17.1 calibration sentence wasn’t sufficient — the model still fixated on embedded ad imagery within newspaper pages.</li>
<li><strong>Form over-prediction (8 instances of form as predicted class):</strong> invoice→form (4), budget→form (2), specification→form (2), scientific_report→form (2), advertisement→form (1). The model defaulted to form when unsure.</li>
<li><strong>scientific_publication→scientific_report (3):</strong> Journal reprint boundary still fuzzy.</li>
<li><strong>Presentation confusion (4):</strong> presentation→memo (2), →handwritten (1), →budget (1) — the model read slide-style layouts as prose memos.</li>
</ul>
<p><strong>Changes:</strong> - <strong>Calibration — form-is-never-a-default.</strong> “If you are choosing form because no other check clearly matched, you have missed a check — go back through checks 1-14.” Addresses the 8 form-overprediction instances. - <strong>Calibration — presentation vs memo.</strong> “A presentation with slide-style layout is presentation, not memo — memo requires internal organizational context and prose body, not slide typography.” Addresses the 2 presentation→memo cases. - <strong>Worked example — invoice with form layout → invoice.</strong> Shows a vendor bill with labeled fields, amount boxes, and approval blocks being classified as invoice because “money function overrides form layout.” Addresses the 4 invoice→form cases. - <strong>Worked example — newspaper page with embedded ad → news_article.</strong> Shows a newspaper page with masthead, columns, bylines, and an embedded brand ad being classified as news_article because “the page’s dominant function is newspaper editorial content.” Addresses the 3 news→ad cases.</p>
<p><strong>Token profile:</strong> +2,216 chars (+4.6% vs v17.1). v17.2 total: 50,678 chars. 8 worked examples total. Still 1,075 chars lighter than v16.</p>
<hr>
</section>
<section id="v0-function-not-subject-baseline-aug-2026" class="level2">
<h2 class="anchored" data-anchor-id="v0-function-not-subject-baseline-aug-2026">v0 — Function-Not-Subject Baseline (Aug 2026)</h2>
<p><strong>Minimal baseline prompt (915 chars) with no check structure — added to benchmark the value of the check-driven iterations (v11+).</strong></p>
<ul>
<li><strong>Content:</strong> Only the “judge by FUNCTION, not subject matter” preamble (commit to the first check with concrete on-page evidence; later checks don’t override) plus the 16 exact label strings. No checks, no worked examples, no calibration sentences.</li>
<li><strong>Purpose:</strong> Isolated control to measure how much of the v17.x accuracy comes from prompt engineering vs.&nbsp;the model’s prior knowledge of document types.</li>
</ul>
<p><strong>Result:</strong> <code>fixed_size_sampled_480</code> slice (30/class × 16 = 480), <code>qwen/qwen3.7-flash</code>, reasoning high, max_tokens 8192: <strong>332/480 (69.2%)</strong>, 0 failed rows. Memo 100%; advertisement/email/scientific_publication 93%; file_folder/news_article 80%; form 73%; letter 70%; resume/scientific_report 60%; invoice/questionnaire/specification 57%; handwritten 53%; budget 43%; presentation 37%.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>RVL-CDIP Document Classifier — AMFAM capstone project</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://github.com/Exios66/AMFAM_capstone">
<p>GitHub</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
<p>Built with Quarto</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>